version: '3.4'

services:
  database:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compras
      MYSQL_USER: LeonSKennedy
      MYSQL_PASSWORD: Chocapic3312
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 3
    networks:
      - app_network
    restart: always
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://LeonSKennedy:Chocapic3312@database/compras
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app_network
    restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/27
